/** Re-export demo fixture helpers. JSON is generated by scripts/export_acmecrm_demo_fixture.py */
export {
  DEMO_FINDING_SLUGS,
  getDemoFindingBySlug,
  getDemoFindingHref,
  getDemoFindingSlug,
  getDemoFindings,
  getDemoReport,
} from "./demo-fixture";
