"""Canonical product analytics event names, keep in sync with packages/shared/src/analytics.ts."""

LANDING_PAGE_VIEWED = "landing_page_viewed"
PRICING_PAGE_VIEWED = "pricing_page_viewed"
SECURITY_PAGE_VIEWED = "security_page_viewed"
FAQ_PAGE_VIEWED = "faq_page_viewed"
FREE_AUDIT_CTA_CLICKED = "free_audit_cta_clicked"
PRICING_CTA_CLICKED = "pricing_cta_clicked"
ENTERPRISE_CTA_CLICKED = "enterprise_cta_clicked"
CONTACT_SALES_CLICKED = "contact_sales_clicked"
CONTACT_SALES_SUBMITTED = "contact_sales_submitted"
FEEDBACK_FAB_CLICKED = "feedback_fab_clicked"
FEEDBACK_FORM_OPENED = "feedback_form_opened"
FEEDBACK_SUBMITTED = "feedback_submitted"
FEEDBACK_PAGE_VIEWED = "feedback_page_viewed"

AUDIT_SESSION_CREATED = "audit_session_created"
AUDIT_STARTED = "audit_started"
AUDIT_CANCELLED = "audit_cancelled"
AUDIT_COMPLETED = "audit_completed"
AUDIT_FAILED = "audit_failed"

CSV_UPLOAD_STARTED = "csv_upload_started"
CSV_UPLOAD_COMPLETED = "csv_upload_completed"
CSV_UPLOAD_FAILED = "csv_upload_failed"
CSV_REMOVED = "csv_removed"
CSV_REPLACED = "csv_replaced"
CSV_VALIDATION_STARTED = "csv_validation_started"
CSV_VALIDATION_COMPLETED = "csv_validation_completed"
CSV_VALIDATION_FAILED = "csv_validation_failed"
CSV_MAPPING_REVIEWED = "csv_mapping_reviewed"
CSV_MAPPING_CORRECTED = "csv_mapping_corrected"

VERIFICATION_STARTED = "verification_started"
VERIFICATION_COMPLETED = "verification_completed"
VERIFICATION_FAILED = "verification_failed"
RULE_EXECUTED = "rule_executed"
RULE_SKIPPED = "rule_skipped"
RULE_FAILED = "rule_failed"
FINDING_CREATED = "finding_created"
FINDING_SUPPRESSED = "finding_suppressed"
COVERAGE_SCORE_CALCULATED = "coverage_score_calculated"

FREE_SUMMARY_VIEWED = "free_summary_viewed"
FREE_SUMMARY_REFRESHED = "free_summary_refreshed"
FINDING_PREVIEW_EXPANDED = "finding_preview_expanded"
REPORT_UNLOCK_CTA_CLICKED = "report_unlock_cta_clicked"
CONTACT_SALES_FROM_RESULTS_CLICKED = "contact_sales_from_results_clicked"

CHECKOUT_STARTED = "checkout_started"
CHECKOUT_COMPLETED = "checkout_completed"
CHECKOUT_FAILED = "checkout_failed"
REPORT_ACCESS_UNLOCKED = "report_access_unlocked"
CONTACT_SALES_FROM_PRICING_CLICKED = "contact_sales_from_pricing_clicked"

PAID_REPORT_VIEWED = "paid_report_viewed"
FINDING_DETAIL_VIEWED = "finding_detail_viewed"
REPORT_EXPORTED_PDF = "report_exported_pdf"
REPORT_EXPORTED_CSV = "report_exported_csv"
REMEDIATION_VIEWED = "remediation_viewed"
