[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh start.sh"
preDeployCommand = "alembic upgrade head"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
